# Generated by Django 4.0.4 on 2022-06-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_description', models.CharField(max_length=250)),
                ('text', models.CharField(max_length=10240)),
                ('author', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ResponseLogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('path', models.CharField(max_length=255)),
                ('status_code', models.PositiveSmallIntegerField()),
                ('response_time', models.PositiveSmallIntegerField(help_text='in milliseconds')),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('employer', models.CharField(max_length=255)),
                ('salary', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=4096)),
                ('job_link', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(max_length=255)),
                ('publication_date', models.DateField()),
            ],
            options={
                'db_table': 'Вакансии',
            },
        ),
    ]
