# Generated by Django 4.0.4 on 2022-07-23 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_job', '0003_alter_vacancy_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(max_length=255),
        ),
    ]
